### ISSUE TITLE
Renovate does not update versions passed through env vars args in `docker-compose.yml`

### ISSUE THREAD

**Issue by AlexSkrypnyk** [drevops/scaffold#1304]
```
  mariadb:
    build:
      context: .
      dockerfile: .docker/mariadb.dockerfile
      args:
        IMAGE: "${DREVOPS_DB_IMAGE:-uselagoon/mariadb-10.11-drupal:24.4.0}"
```
