### ISSUE TITLE
Automatically update consumer sites on Scaffold release

### ISSUE THREAD

**Issue by AlexSkrypnyk** [drevops/scaffold#1321]
We want the consumer sites to have PRs open with updates automatically when the Scaffold has a new version.

https://github.com/drevops/scaffold/issues/1042 will allow to manually update Scaffold as a dependency on the consumer projects when there is a new Scaffold release via `composer update drevops/scaffold`.

Renovate config could pick up this update, but it will not run the plugins that would trigger the files updates. So Renovate cannot be used for this :(

The solution is to ship a custom GHA for a consumer site. The GHA would:
1. Run on schedule daily to check for new versions of `drevops/scaffold` by running `composer update drevops/scaffold`.
2. If there are changes found (the changes would be the updated files coming from Scaffol and auto-customised for the repo) - they will be committed to the repo in a new PR.
3. Wrap this into action

Note that this is a monetisation feature of Scaffold. The first month or two will be for free. A token would need to be generated to use this.

Starting point

```yaml
name: Synchronize Package Updates

on:
  schedule:
    # Runs every day at 05:00 UTC
    - cron:  '0 5 * * *'
  workflow_dispatch:

jobs:
  sync-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout consumer repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Clone package repository
        run: |
          git clone https://github.com/yourusername/your-package-repo.git ./external-package

      - name: Copy updated files
        run: |
          cp -r ./external-package/path/to/files/* ./path/in/consumer/repo/

      - name: Check for changes
        id: file-check
        run: |
          if git diff --quiet; then
            echo "No changes detected."
            echo "has_changes=no" >> $GITHUB_ENV
          else
            echo "Changes detected."
            echo "has_changes=yes" >> $GITHUB_ENV

      - name: Commit and push if changes are detected
        if: env.has_changes == 'yes'
        run: |
          git checkout -b update-branch
          git add .
          git commit -m "Automatically update package files"
          git push origin update-branch

      - name: Create Pull Request
        if: env.has_changes == 'yes'
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Automatically update package files"
          pr_body: "This is an auto-generated PR with updates from external package."
          pr_label: "auto-update"
          pr_branch: "update-branch"
          pr_reviewer: "username1,username2"  # Optional: Add reviewers if needed
          pr_assignee: "username"  # Optional: Assign to a user

```
