### ISSUE TITLE
Increase Codecov threshold to be more than 1% to reduce false-positives

### ISSUE THREAD

**Issue by AlexSkrypnyk** [drevops/scaffold#1347]
Investigate if this can be done in the CI config or if the per-repo yaml file is required.

**Comment by AlexSkrypnyk** [comment]
```yaml
coverage:
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        threshold: 1%
```

Added as a global directly into Codecov UI.
